### PR TITLE
Running sum of 1D Array

### PR DESCRIPTION
**Pull request by yusufom**
Solution for Running sum of 1D Array exercise

### CODE REVIEW

**Review by AdebayoEmmanuel — DISMISSED** [review]

**Review by PME-Community — COMMENTED** [review]
@yusufom Kindly rename the image file. It should have the same name as the class for easy reference. Thank you

**Comment by yusufom** [comment]
> @yusufom Kindly rename the image file. It should have the same name as the class for easy reference. Thank you

@PME-Community I'd like to clarify, when you mean class, is it the title of the question, or the class name in the solution?

**Comment by PME-Community** [comment]
@yusufom  in your case, the title of the question.

**Review by PME-Community — APPROVED** [review]

**Review by richkazz — APPROVED** [review]

**Comment by yusufom** [comment]
> @yusufom  in your case, the title of the question. 

Done

**Comment by AdebayoEmmanuel** [comment]
do you want the branch deleted, or you still wan dey use am?

**Comment by yusufom** [comment]
I'll have it as my permanent branch

**Pull request merged**
